name: NuttX issue template
description: Submit a bug report.
labels: [bug]
body:

  - type: textarea
    attributes:
      label: "Problem"
      description: "Describe the current behavior. May include logs, images, or videos."
    validations:
      required: true