# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: Docker Nuttx test

permissions:
  contents: read
on: 
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/dockerfile_test.yml'

jobs:
  build_docker_test:
    container: ghcr.io/simbit18/nuttx-testing-ci/apache-nuttx-ci-linux
    runs-on: ubuntu-latest
    steps:
      - name: System Information
        run: |
          bash --version
          uname -a
      - name: Set Environment Variables
        run: |
          echo "$GITHUB_PATH"
          echo "$PATH"
          # arm-none-eabi-gcc --version
          # aarch64-none-elf-gcc --version
      - name: Checkout Source Files
        uses: actions/checkout@v4
        run: |
          echo 'Checkout Source Files'
          mkdir nuttxspace
          ls -a
          cd nuttxspace
          # git clone --depth 1 https://github.com/ramangopalan/nuttx.git nuttx
          # git clone --depth 1 https://github.com/ramangopalan/nuttx-apps.git apps
          git clone --depth 1 https://github.com/simbit18/nuttx.git nuttx
          git clone --depth 1 https://github.com/simbit18/nuttx-apps.git apps

          ls -a

      - name: Build
        run: |
          echo 'Build'

          ## Move to nuttx
          cd nuttxspace/nuttx
          ls -a

          ## Show the GCC version
          gcc -v

          ## Show the avr32-gcc version
          avr32-gcc --version
          avr32-gcc -dumpspecs

          ## Configure the build
          ## ./tools/configure.sh -l mizar32a:nsh
          ./tools/configure.sh -l -S mizar32a:nsh

          ## mkdir nuttxmsys2

          ## Preserve the build config
          ## cp .config nuttxmsys2/nuttx.config
          make -j
          ls -a
          
          make distclean -j
          
          ./tools/configure.sh -l -S esp32-devkitc:nsh
          
          make -j
          ls -a
          
          make distclean -j
          
          ./tools/configure.sh -l esp32-devkitc:nsh
          
          make -j
          ls -a
