# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: Docker GN test

permissions:
  contents: read
on: 
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/dockerfile_gn_test.yml'

jobs:
  build_docker_test:
    container: ghcr.io/simbit18/nuttx-testing-ci/apache-nuttx-ci-linux
    runs-on: ubuntu-latest
    steps:
      - name: System Information
        run: |
          bash --version
          uname -a
      - name: Set Environment Variables
        run: |
          echo "$GITHUB_PATH"
          echo "$PATH"
          # arm-none-eabi-gcc --version
          # aarch64-none-elf-gcc --version
      - name: Test version
        run: |
          echo 'Version'

          ## Show the GCC version
          # gcc -v

          ## Show the avr32-gcc version
          # avr32-gcc --version
          # avr32-gcc -dumpspecs

          ## Show the gn version
          gn --version
          gn --help

          ## Show the picotool version
          picotool version
          picotool help


